name: 'Bump Version'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version on main'
    # Prefix with "MAJOR:" to bump major
    # "MINOR:" or "FEAT:" bump minor
    # "PRE-ALPHA:", "PRE-BETA:", "PRE-RC:" bump pre-release version
    # Anything else bumps patch version
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          minor-wording: 'MINOR,FEAT'
          major-wording: 'MAJOR,BREAKING'
          patch-wording: 'PATCH,FIXES'
          rc-wording: 'PRE-ALPHA,PRE-BETA,PRE-RC'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
